server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fjapp
    username: postgres
    password: 1441
  data:
    redis:
      url: redis://127.0.0.1:6379

logging:
  config: src/main/resources/logback-spring.xml

